# Generated by Django 2.2 on 2021-03-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dojo',
            table='db_test',
        ),
    ]
